{ pkgs, ... }:

{
  # Enable nixld for running dynamically linked binaries
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      stdenv.cc.cc
      zlib
      fuse3
      alsa-lib
      at-spi2-atk
      at-spi2-core
      atk
      cairo
      cups
      curl
      dbus
      expat
      fontconfig
      freetype
      gdk-pixbuf
      glib
      gtk3
      harfbuzz
      keybinder3
      libGL
      libappindicator-gtk3
      libdrm
      libdecor
      libepoxy
      libnotify
      libayatana-appindicator
      libayatana-indicator
      ayatana-ido
      libpulseaudio
      libdbusmenu
      libuuid
      libxcb-cursor
      libxcb-util
      libxcb-render-util
      libxcb-image
      libxcb-keysyms
      libxcb-wm
      xorg.libxcb
      libxkbcommon
      mesa
      nspr
      nss
      pango
      pipewire
      systemd
      icu
      openssl
      xorg.libX11
      xorg.libXScrnSaver
      xorg.libXcomposite
      xorg.libXcursor
      xorg.libXdamage
      xorg.libXext
      xorg.libXfixes
      xorg.libXi
      xorg.libXinerama
      xorg.libXrandr
      xorg.libXrender
      xorg.libXtst
      xorg.libxkbfile
      xorg.libxshmfence
      xorg.libXxf86vm
      zlib
      SDL2
      SDL2_image
      pkgsi686Linux.glibc
      pkgsi686Linux.openssl
      pkgsi686Linux.curl      
      pkgsi686Linux.zlib
    ];
  };
}
