{ pkgs, ... }:

{
  # Enable nixld for running dynamically linked binaries
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      stdenv.cc.cc
      zlib
      fuse3
      alsa-lib
      at-spi2-atk
      at-spi2-core
      atk
      cairo
      cups
      curl
      dbus
      expat
      fontconfig
      freetype
      gdk-pixbuf
      glib
      gtk3
      harfbuzz
      keybinder3
      libGL
      libappindicator-gtk3
      curlWithGnuTls
      libdrm
      libdecor
      libepoxy
      libnotify
      libayatana-appindicator
      libayatana-indicator
      ayatana-ido
      libpulseaudio
      libdbusmenu
      libuuid
      libxcb-cursor
      libxcb-util
      libxcb-render-util
      libxcb-image
      libxcb-keysyms
      libxcb-wm
      libxcb
      libxkbcommon
      mesa
      nspr
      nss
      pango
      pipewire
      systemd
      icu
      openssl
      openal
      libX11
      libXScrnSaver
      libXcomposite
      libXcursor
      libXdamage
      libXext
      libXfixes
      libXi
      libXinerama
      libXrandr
      libXrender
      libXtst
      libxkbfile
      libxshmfence
      libXxf86vm
      zlib
      SDL2
      SDL2_image
      pkgsi686Linux.glibc
      pkgsi686Linux.openssl
      pkgsi686Linux.curl
      pkgsi686Linux.zlib
    ];
  };
}
